apiVersion: v1
kind: Service
metadata:
  name: mywebapps-service
  labels:
    app: mywebapps
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebapps
  type: ClusterIP
